### ISSUE TITLE
x4c/SoftNPU: Remote Access Preview MVP

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/p4#2]
This is a tracking issue for the minimum viable product (MVP) needed for the remote access preview (RAP).

At a high level, the RAP requires 
- [x] ~Compilation of the [Sidecar P4 code](https://github.com/oxidecomputer/dendrite/tree/main/dpd/p4) into a complete P4 AST.~ Compilation of [Sidecar-lite P4 code](https://github.com/oxidecomputer/p4/blob/main/test/src/p4/sidecar-lite.p4)
- [x] Generation of Rust packet pipeline code from the Sidecar P4 AST.
- [x] Execution of the Sidecar Rust packet pipeline code in the SoftNPU pipeline execution harness which provides network I/O through the pipelines.
- [x] Implementation of SoftNPU as Propolis device (logistically similar to the current [sidemux](https://github.com/oxidecomputer/propolis/blob/falcon/propolis/src/hw/virtio/sidemux.rs) Propolis device)
- [x] ~Implementation of the necessary [Barefoot SDE functions](https://github.com/oxidecomputer/dendrite/blob/main/bf/imported_bf_functions) for DPD to run atop SoftNPU running as a Propolis device.~ Implment AAL interface in dendrite/asic/softnpu.

Note: Not considering full sidecar compilation as a blocker for MVP. Execution of `sidecar-lite.p4` is sufficient for RAP purposes. In the fullness of time, we'll want `sidecar-lite.p4` to go away. But this is not a blocker for RAP MVP.

## Milestones

The Sidecar P4 code is relatively complex. And we'll not start by jumping into that code directly. The following are a series of milestones that build up to running the Sidecar P4 code from x4c (the compiler contained in this repo) compiled code and running that code on a Propolis-based SoftNPU device.

### SoftNPU Packet Hub
This is a simple hub, i.e. a switch that broadcasts any packet it receives on all the ports that it has.

- [x] AST generation
- [x] Rust packet pipeline code generation.
- [x] SoftNPU Execution
- [x] Automated test coverage.

### SoftNPU Packet Router
This is a simple router that has a pair of tables for IPv4 and IPv6 for longest prefix match (LPM) routing. IPv6 is the priority here.

- [x] AST generation
- [x] Rust packet pipeline code generation.
- [x] SoftNPU Execution
- [x] Automated test coverage.

### SoftNPU Packet Router with Services and CPU Port
This builds on the previous Packet router. In addition to pure LPM routing, a services table is added which contains a combination of ternary and exact packet classifiers that can direct packets to custom service actions, some of which include forwarding to and from a special CPU port. Packets going to/from the CPU port will also carry the Sidecar header like they do in our existing Sidecar P4 code.

- [x] AST generation
- [x] Rust packet pipeline code generation.
- [x] SoftNPU Execution
- [x] Automated test coverage.

### Packet Encapsulation and NAT
- [x] AST generation
- [x] Rust packet pipeline code generation.
- [x] SoftNPU Execution
- [x] TCP/UDP NAT
- [x] ICMP NAT

## P4 Compiler Internals

The above tasks identify milestones on the path to victory. This section lists tasks that need to be accomplished inside the compiler for the above to work.

- [x] Ternary classification support in the ~[HiCuts](https://github.com/oxidecomputer/p4/blob/main/lang/p4rs/src/hicuts.rs)~ decision tree.
- [x] LPM classification support in the ~[HiCuts](https://github.com/oxidecomputer/p4/blob/main/lang/p4rs/src/hicuts.rs)~ decision tree.
- [x] Scalable pipeline observability (e.g. not the firehose or nothing approach of the Tofino sim). Leveraging the [usdt crate](https://github.com/oxidecomputer/usdt) seems like a good place to start here.
- [x] ~Complete `Expression` parsing, e.g. all the various operations that can happen on packet fields and variables.~ Not blocker for RAP MVP
- [x] ~Complete `Expression` code generation.~ Not blocker for RAP MVP.
